# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

signCPP <- function(x) {
    .Call(`_sparseKOS_signCPP`, x)
}

SoftThreshCPP <- function(x, lambda) {
    .Call(`_sparseKOS_SoftThreshCPP`, x, lambda)
}

CoordDesCPP <- function(w0, Q, beta, lambda, epsln, maxniter = 1.0e7) {
    .Call(`_sparseKOS_CoordDesCPP`, w0, Q, beta, lambda, epsln, maxniter)
}

SolveKOSCPP <- function(YTheta, K, gammaKOS, epsilonKOS = 1e-5) {
    .Call(`_sparseKOS_SolveKOSCPP`, YTheta, K, gammaKOS, epsilonKOS)
}

DerivCPP <- function(x, Data, w0, sigmaD) {
    .Call(`_sparseKOS_DerivCPP`, x, Data, w0, sigmaD)
}

TMatCPP <- function(Data, A, w0, sigmaTm) {
    .Call(`_sparseKOS_TMatCPP`, Data, A, w0, sigmaTm)
}

ObjectiveFuncCPP <- function(w, KwOF, Data, DVectors, YTheta, lambdaOF, gammaOF, epsilonOF = 1e-5) {
    .Call(`_sparseKOS_ObjectiveFuncCPP`, w, KwOF, Data, DVectors, YTheta, lambdaOF, gammaOF, epsilonOF)
}

